
class DaysEnum(Enum):
	monday = "Monday"
	tuesday = "Tuesday"
	wednesday = "Wednesday"
	thursday = "Thursday"
	friday = "Friday"
	saturday = "Saturday"
	sunday = "Sunday"

class InterestsEnum(Enum):
	youth = "Youth"
	seniors = "Seniors"
	education ="Education"
	environment = "Environment/Sustainability"
	health = "Health"
	arts = "Arts and Culture"
	financialemp = "Financial Empowerment"
	veterans = "Veterans"
	immigration = "Immigration"
	animals = "Animals"
	mentoring = "Mentoring"
	homeless = "Homeless/Housing"
	lgbt = "Lesbian, gay, bisexual, transgender"
	domestic = "Domestic Violence"
	hunger = "Hunger"
	disabilities = "People with Disabilities"

class SkillsEnum(Enum):
	public = "Public Relations/Public Speaking"
	teaching = "Teaching/Tutoring"
	it = "IT/Computer"
	administrative = "Administrative"
	legal = "Legal"
	coaching ="Coaching/Mentoring"
	handiwork = "Handiwork"
	arts = "Fine Arts"
	tefl = "TEFL/TESOL"
	writing = "Writing/Editing"
	language = "Foreign Language"
	event = "Event Planning"
	management = "Management"
	sports = "Sports/Recreation"

class NeighborhoodsEnum(Enum):
	allston ="Allston"
	backbay = "Back Bay"
	bayvillage = "Bay Village"
	beacon = "Beacon Hill"
	brighton = "Brighton"
	charlestown = "Charlestown"
	chinatown = "Chinatown/Leather District"
	dorchester = "Dorchester"
	downtown = "Downtown"
	eastboston = "East Boston"
	fenwaykenmore = "Fenway Kenmore"
	hyde = "Hyde Park"
	jamaica = "Jamaica Plain"
	mattapan = "Mattapan"
	misdorchester = "Mid Dorchester"
	missionshill = "Mission Hill"
	northend = "North End"
	roslindale = "Roslindale"
	roxbury = "Roxbury"
	southboston = "South Boston"
	southend = "South End"
	westend = "West End"
	westroxbury = "West Roxbury"
	greater = "Greater Boston Area/Outside City"

	class EducationEnum(Enum):
	lesshigh = "Less than High School"
	highschool = "High School diploma or equivalent"
	somecoll = "Some college, no degree"
	postsec = "Postsecondary non-degree award"
	associate = "Associate's degree"
	bachelor = "Bachelor's degree"
	master = "Master's degree"
	doctoral = "Doctoral or professional degree"